# Generated by Django 4.2 on 2023-04-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publication_dt', models.CharField(max_length=255)),
                ('book_image', models.URLField()),
                ('description', models.TextField()),
                ('publisher', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='searchresult',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='publication_dt',
            field=models.CharField(default='', max_length=255),
        ),
    ]
