# Generated by Django 4.2 on 2023-04-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
