# Generated by Django 4.2 on 2023-04-18 23:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_booklist_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='comment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
